// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: solution_hub.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SolveProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ProblemType   string                 `protobuf:"bytes,2,opt,name=problem_type,json=problemType,proto3" json:"problem_type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolveProblemRequest) Reset() {
	*x = SolveProblemRequest{}
	mi := &file_solution_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolveProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolveProblemRequest) ProtoMessage() {}

func (x *SolveProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_solution_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolveProblemRequest.ProtoReflect.Descriptor instead.
func (*SolveProblemRequest) Descriptor() ([]byte, []int) {
	return file_solution_hub_proto_rawDescGZIP(), []int{0}
}

func (x *SolveProblemRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SolveProblemRequest) GetProblemType() string {
	if x != nil {
		return x.ProblemType
	}
	return ""
}

func (x *SolveProblemRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SolveProblemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SolveProblemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolveProblemResponse) Reset() {
	*x = SolveProblemResponse{}
	mi := &file_solution_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolveProblemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolveProblemResponse) ProtoMessage() {}

func (x *SolveProblemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_solution_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolveProblemResponse.ProtoReflect.Descriptor instead.
func (*SolveProblemResponse) Descriptor() ([]byte, []int) {
	return file_solution_hub_proto_rawDescGZIP(), []int{1}
}

func (x *SolveProblemResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SolveProblemResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SolveProblemResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *SolveProblemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_solution_hub_proto protoreflect.FileDescriptor

const file_solution_hub_proto_rawDesc = "" +
	"\n" +
	"\x12solution_hub.proto\x12\vsolutionhub\"\x84\x01\n" +
	"\x13SolveProblemRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\fproblem_type\x18\x02 \x01(\tR\vproblemType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"y\n" +
	"\x14SolveProblemResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess2b\n" +
	"\vSolutionHub\x12S\n" +
	"\fSolveProblem\x12 .solutionhub.SolveProblemRequest\x1a!.solutionhub.SolveProblemResponseB1Z!gmhelper.solution-hub/proto;proto\xaa\x02\vSolutionHubb\x06proto3"

var (
	file_solution_hub_proto_rawDescOnce sync.Once
	file_solution_hub_proto_rawDescData []byte
)

func file_solution_hub_proto_rawDescGZIP() []byte {
	file_solution_hub_proto_rawDescOnce.Do(func() {
		file_solution_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_solution_hub_proto_rawDesc), len(file_solution_hub_proto_rawDesc)))
	})
	return file_solution_hub_proto_rawDescData
}

var file_solution_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_solution_hub_proto_goTypes = []any{
	(*SolveProblemRequest)(nil),  // 0: solutionhub.SolveProblemRequest
	(*SolveProblemResponse)(nil), // 1: solutionhub.SolveProblemResponse
}
var file_solution_hub_proto_depIdxs = []int32{
	0, // 0: solutionhub.SolutionHub.SolveProblem:input_type -> solutionhub.SolveProblemRequest
	1, // 1: solutionhub.SolutionHub.SolveProblem:output_type -> solutionhub.SolveProblemResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_solution_hub_proto_init() }
func file_solution_hub_proto_init() {
	if File_solution_hub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_solution_hub_proto_rawDesc), len(file_solution_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_solution_hub_proto_goTypes,
		DependencyIndexes: file_solution_hub_proto_depIdxs,
		MessageInfos:      file_solution_hub_proto_msgTypes,
	}.Build()
	File_solution_hub_proto = out.File
	file_solution_hub_proto_goTypes = nil
	file_solution_hub_proto_depIdxs = nil
}
