// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0--rc2
// source: solution_hub.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SolutionHub_SolveProblem_FullMethodName = "/solutionhub.SolutionHub/SolveProblem"
)

// SolutionHubClient is the client API for SolutionHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolutionHubClient interface {
	SolveProblem(ctx context.Context, in *SolveProblemRequest, opts ...grpc.CallOption) (*SolveProblemResponse, error)
}

type solutionHubClient struct {
	cc grpc.ClientConnInterface
}

func NewSolutionHubClient(cc grpc.ClientConnInterface) SolutionHubClient {
	return &solutionHubClient{cc}
}

func (c *solutionHubClient) SolveProblem(ctx context.Context, in *SolveProblemRequest, opts ...grpc.CallOption) (*SolveProblemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SolveProblemResponse)
	err := c.cc.Invoke(ctx, SolutionHub_SolveProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolutionHubServer is the server API for SolutionHub service.
// All implementations must embed UnimplementedSolutionHubServer
// for forward compatibility.
type SolutionHubServer interface {
	SolveProblem(context.Context, *SolveProblemRequest) (*SolveProblemResponse, error)
	mustEmbedUnimplementedSolutionHubServer()
}

// UnimplementedSolutionHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSolutionHubServer struct{}

func (UnimplementedSolutionHubServer) SolveProblem(context.Context, *SolveProblemRequest) (*SolveProblemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SolveProblem not implemented")
}
func (UnimplementedSolutionHubServer) mustEmbedUnimplementedSolutionHubServer() {}
func (UnimplementedSolutionHubServer) testEmbeddedByValue()                     {}

// UnsafeSolutionHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolutionHubServer will
// result in compilation errors.
type UnsafeSolutionHubServer interface {
	mustEmbedUnimplementedSolutionHubServer()
}

func RegisterSolutionHubServer(s grpc.ServiceRegistrar, srv SolutionHubServer) {
	// If the following call panics, it indicates UnimplementedSolutionHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SolutionHub_ServiceDesc, srv)
}

func _SolutionHub_SolveProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionHubServer).SolveProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolutionHub_SolveProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionHubServer).SolveProblem(ctx, req.(*SolveProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SolutionHub_ServiceDesc is the grpc.ServiceDesc for SolutionHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolutionHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "solutionhub.SolutionHub",
	HandlerType: (*SolutionHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SolveProblem",
			Handler:    _SolutionHub_SolveProblem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "solution_hub.proto",
}
